### ISSUE TITLE
New Stories

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/storybook#1]
A free creative task for everyone, this project is really new and I'd like to add more stories to the storybook. Be creative showing cool things done with [tsParticles](https://github.com/matteobruni/tsparticles)

**Comment by Enhmunh-E** [comment]
Hello, I would like to know how to contribute to this repository, please. As I see clone the project and start the development All I can see is a start page from react template.

**Comment by Enhmunh-E** [comment]
If it is possible I would like to write a contribution guideline and such.

**Comment by Enhmunh-E** [comment]
And by the way, is there any way to contact you through discord? I think that you had a discord account last year. Is it still available?

**Comment by matteobruni** [comment]
> Hello, I would like to know how to contribute to this repository, please. As I see clone the project and start the development All I can see is a start page from react template.

It's a simple storybook project, you can read more here how it works: https://storybook.js.org
